### ISSUE TITLE
Ontology Annotations not rendering and RAT-C error - gate 8.5 OAT plugin

### ISSUE THREAD

**Issue by Simo-climb** [GateNLP/gateplugin-Ontology#1]
Hi folks

I've just loaded up gate 8.5 to use the ontology annotation tools.

However the annotations are not rendering in the OAT view or RAT-C or RAT-I. Annotations do show in the document annotation set

I found the below post who also had this issue in Jan 2019, but there was no response on the sourceforge archive or the new groups.io list. (See below)

I receive the same error as referred to below when trying to use the RAT-C tool.

Is this a current issue or are there other config settings to resolve this?

I'm using windows 10.

Regards

Simon

 

[OLD gate-users] Ontology Annotation Tools (OAT) for GATE 8.5.1 does not seem to render annotationsFrom: Licheng Zeng <zeng.licheng@gm...> - 2019-01-27 00:33:00Attachments: image.png image.png Message as HTML
--
Hi,  I am experimenting with Ontology and Ontology Tools plugins of GATE 8.5.1.  I tried to annotate a text using OAT and RAT-C. I experienced the following issues:  1) annotations do not seem to render in OAT. I selected "what is a tree dispute" text and annotate it. The annotation can be rendered in the "Annotation Sets" view. [image: image.png] However it couldn't be rendered in the "OAT" view [image: image.png]  2) the second problem is that when I tried to open the RAT-C view to edit relations, there was a runtime error with the following message: Exception in thread "AWT-EventQueue-0" java.lang.IllegalAccessError: tried to access field gate.gui.docview.DocumentEditor.horizontalViews from class gate.gui.docview.OntologyClassView at gate.gui.docview.OntologyClassView.registerHooks(OntologyClassView.java:263) at gate.gui.docview.AbstractDocumentView.setActive(AbstractDocumentView.java:53) at gate.gui.docview.DocumentEditor.setRightView(DocumentEditor.java:749) at gate.gui.docview.DocumentEditor$ViewButton$1.actionPerformed(DocumentEditor.java:1307) at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308) at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289) at java.awt.Component.processMouseEvent(Component.java:6539) at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) at java.awt.Component.processEvent(Component.java:6304) at java.awt.Container.processEvent(Container.java:2239) at java.awt.Component.dispatchEventImpl(Component.java:4889) at java.awt.Container.dispatchEventImpl(Container.java:2297) at java.awt.Component.dispatchEvent(Component.java:4711) at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904) at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535) at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476) at java.awt.Container.dispatchEventImpl(Container.java:2283) at java.awt.Window.dispatchEventImpl(Window.java:2746) at java.awt.Component.dispatchEvent(Component.java:4711) at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760) at java.awt.EventQueue.access$500(EventQueue.java:97) at java.awt.EventQueue$3.run(EventQueue.java:709) at java.awt.EventQueue$3.run(EventQueue.java:703) at java.security.AccessController.doPrivileged(Native Method) at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84) at java.awt.EventQueue$4.run(EventQueue.java:733) at java.awt.EventQueue$4.run(EventQueue.java:731) at java.security.AccessController.doPrivileged(Native Method) at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) at java.awt.EventQueue.dispatchEvent(EventQueue.java:730) at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)  I thought it could be my installation/configuration issue so I uninstalled GATE 8.5.1 and repeated the process of installation and testing. I still experienced the same problem. Note that I tried with GATE 8.4.1. The Onotology plugins are all working properly.  Is there something I missed or could there be a defect?  regards Licheng

**Comment by Simo-climb** [comment]
Just upgraded to gate 8.6

no change to the reported issue. Ontology annotations not showing and receiving the below error when instantiating the RAT-C tool

GATE 8.6 build 86a246c started at Sat Aug 03 03:09:46 AEST 2019
and using Java 10.0.1 Oracle Corporation on Windows 10 amd64 10.0.
CREOLE plugin loaded: Document Normalizer 8.5
CREOLE plugin loaded: Annotation Merging 8.5
Storing data in folder: C:\Users\simon\Documents\GitHub\Agent Model_TBCME_6.2.2\DMM_AgentOritentedModels0.001\AIIMS\GateDataDirectory\GATE_OWLIMOntology_jyuddjkp0
Using config file: C:\Users\simon\Documents\CREOLE Plugins\gateplugin-Ontology-8.5\config\owlim-max-nopartial.ttl
org.slf4j.LoggerFactory is available via both the system classpath and a plugin; the plugin (file:/C:/Users/simon/Documents/CREOLE%20Plugins/gateplugin-Ontology-8.5/) classes will be ignored
org.slf4j.Logger is available via both the system classpath and a plugin; the plugin (file:/C:/Users/simon/Documents/CREOLE%20Plugins/gateplugin-Ontology-8.5/) classes will be ignored
ruleSet=owl-max, partialRdfs=false
Default name space is http://surroundaustralia.org/disastermanagement/australia/doctrine/def/
Exception in thread "AWT-EventQueue-0" java.lang.IllegalAccessError: tried to access field gate.gui.docview.DocumentEditor.horizontalViews from class gate.gui.docview.OntologyClassView
	at gate.gui.docview.OntologyClassView.registerHooks(OntologyClassView.java:263)
	at gate.gui.docview.AbstractDocumentView.setActive(AbstractDocumentView.java:53)
	at gate.gui.docview.DocumentEditor.setRightView(DocumentEditor.java:749)
	at gate.gui.docview.DocumentEditor$ViewButton$1.actionPerformed(DocumentEditor.java:1307)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:401)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6589)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6354)
	at java.desktop/java.awt.Container.processEvent(Container.java:2261)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4966)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2319)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4914)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4543)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4484)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2305)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4798)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.IllegalAccessError: tried to access field gate.gui.docview.AbstractDocumentView.document from class gate.gui.docview.OntologyClassView$MouseStoppedMovingAction
	at gate.gui.docview.OntologyClassView$MouseStoppedMovingAction.actionPerformed(OntologyClassView.java:797)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by ianroberts** [comment]
I've found the problem and I'm working on fixing it, it's an artifact of changes to exactly which classes are on which classloaders.
